config/routes.rb
Rails.application.routes.draw do
  resources :hoges
  namespace :foo do
    resources :bars
  end

end

app/models/hoge.rb
class Hoge < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foo/bars_controller.rb
class Foo::BarsController < ApplicationController
  # GET /hoges
  # GET /hoges.json
  def index
  end

  # GET /hoges/1
  # GET /hoges/1.json
  def show
  end

  # GET /hoges/new
  def new
    @hoge = Hoge.new
  end

  # GET /hoges/1/edit
  def edit
  end

  # POST /hoges
  # POST /hoges.json
  def create
  end

  # PATCH/PUT /hoges/1
  # PATCH/PUT /hoges/1.json
  def update
  end

  # DELETE /hoges/1
  # DELETE /hoges/1.json
  def destroy
  end
end

app/controllers/hoges_controller.rb
class HogesController < ApplicationController
  before_action :set_hoge, only: [:show, :edit, :update, :destroy]

  # GET /hoges
  # GET /hoges.json
  def index
    @hoges = Hoge.all
  end

  # GET /hoges/1
  # GET /hoges/1.json
  def show
  end

  # GET /hoges/new
  def new
    @hoge = Hoge.new
  end

  # GET /hoges/1/edit
  def edit
  end

  # POST /hoges
  # POST /hoges.json
  def create
    @hoge = Hoge.new(hoge_params)

    respond_to do |format|
      if @hoge.save
        format.html { redirect_to @hoge, notice: 'Hoge was successfully created.' }
        format.json { render :show, status: :created, location: @hoge }
      else
        format.html { render :new }
        format.json { render json: @hoge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /hoges/1
  # PATCH/PUT /hoges/1.json
  def update
    respond_to do |format|
      if @hoge.update(hoge_params)
        format.html { redirect_to @hoge, notice: 'Hoge was successfully updated.' }
        format.json { render :show, status: :ok, location: @hoge }
      else
        format.html { render :edit }
        format.json { render json: @hoge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hoges/1
  # DELETE /hoges/1.json
  def destroy
    @hoge.destroy
    respond_to do |format|
      format.html { redirect_to hoges_url, notice: 'Hoge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hoge
      @hoge = Hoge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def hoge_params
      params[:hoge]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hoges_helper.rb
module HogesHelper
end

app/views/foo/bars/index.html.erb
<h1>Listing Bars</h1>

app/views/hoges/_form.html.erb
<%= form_for(@hoge) do |f| %>
  <% if @hoge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@hoge.errors.count, "error") %> prohibited this hoge from being saved:</h2>

      <ul>
      <% @hoge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/hoges/edit.html.erb
<h1>Editing Hoge</h1>

<%= render 'form' %>

<%= link_to 'Show', @hoge %> |
<%= link_to 'Back', hoges_path %>

app/views/hoges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Hoges</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @hoges.each do |hoge| %>
      <tr>
        <td><%= link_to 'Show', hoge %></td>
        <td><%= link_to 'Edit', edit_hoge_path(hoge) %></td>
        <td><%= link_to 'Destroy', hoge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Hoge', new_hoge_path %>

app/views/hoges/new.html.erb
<h1>New Hoge</h1>

<%= render 'form' %>

<%= link_to 'Back', hoges_path %>

app/views/hoges/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_hoge_path(@hoge) %> |
<%= link_to 'Back', hoges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsSampleProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>